# Generated by Django 3.1.2 on 2020-10-31 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20201031_2328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teacher',
            new_name='teacher1',
        ),
    ]
