# Generated by Django 3.1.2 on 2020-10-31 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20201101_0006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teacher1',
            new_name='teacher',
        ),
    ]
