# Generated by Django 3.1.2 on 2020-11-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_mteacher_sateacher_steacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='resultslider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yr', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
